"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
var types_1 = require("../../src/controller/types");
var mock_controller_settings_1 = require("../common/mock-controller-settings");
var boiler_1 = require("../../src/controller/devices/boiler");
var ch_pump_1 = require("../../src/controller/devices/ch-pump");
var hw_pump_1 = require("../../src/controller/devices/hw-pump");
exports.container = new inversify_1.Container();
exports.container.bind(types_1.INJECTABLES.SlotsPerDay).toConstantValue(10);
exports.container.bind(types_1.INJECTABLES.ControllerSettings).to(mock_controller_settings_1.MockControllerSettings).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.Boiler).to(boiler_1.Boiler).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.CHPump).to(ch_pump_1.CHPump).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.HWPump).to(hw_pump_1.HWPump).inSingletonScope();
