"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
var types_1 = require("../../src/controller/types");
var boiler_1 = require("../../src/controller/boiler");
var ch_pump_1 = require("../../src/controller/ch-pump");
var hw_pump_1 = require("../../src/controller/hw-pump");
var mocks_1 = require("./mocks");
var mock_controller_settings_1 = require("../common/mock-controller-settings");
exports.container = new inversify_1.Container();
exports.container.bind(types_1.INJECTABLES.DigitalOutput).to(mocks_1.MockDigitalOutput).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.ControllerSettings).to(mock_controller_settings_1.MockControllerSettings).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.Boiler).to(boiler_1.Boiler).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.CHPump).to(ch_pump_1.CHPump).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.HWPump).to(hw_pump_1.HWPump).inSingletonScope();
