"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
require("reflect-metadata");
var override_manager_1 = require("../../src/controller/override-manager");
var types_1 = require("../../src/controller/types");
var mock_clock_1 = require("../common/mock-clock");
var mock_controller_settings_1 = require("../common/mock-controller-settings");
exports.container = new inversify_1.Container();
exports.container.bind(types_1.INJECTABLES.SlotsPerDay).toConstantValue(10);
exports.container.bind(types_1.INJECTABLES.OverrideManager).to(override_manager_1.OverrideManager).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.ControllerSettings).to(mock_controller_settings_1.MockControllerSettings).inSingletonScope();
exports.container.bind(types_1.INJECTABLES.Clock).to(mock_clock_1.MockClock).inSingletonScope();
